import sqlite3 from 'sqlite3';
import { runQuery } from './db';

export async function createTablePoolKeys(db: sqlite3.Database) {
  const sql = `CREATE TABLE IF NOT EXISTS poolKeys (
                 poolId TEXT PRIMARY KEY,
                 baseMint TEXT,
                 quoteMint TEXT,
                 lpMint TEXT,
                 baseDecimals INTEGER,
                 quoteDecimals INTEGER,
                 lpDecimals INTEGER,
                 version INTEGER,
                 programId TEXT,
                 authority TEXT,
                 openOrders TEXT,
                 targetOrders TEXT,
                 baseVault TEXT,
                 quoteVault TEXT,
                 marketVersionId INTEGER,
                 marketProgramId TEXT,
                 marketId TEXT,
                 marketAuthority TEXT,
                 marketBaseVault TEXT,
                 marketQuoteVault TEXT,
                 marketBids TEXT,
                 marketAsks TEXT,
                 marketEventQueue TEXT,
                 withdrawQueue TEXT,
                 lpVault TEXT,
                 lookupTableAccount TEXT )`;
  await runQuery(db, sql);
}

export async function insertPoolKeys(db: sqlite3.Database, poolKeys: any) {
  const sql = `INSERT OR IGNORE INTO poolKeys (
                 poolId,
                 baseMint,
                 quoteMint,
                 lpMint,
                 baseDecimals,
                 quoteDecimals,
                 lpDecimals,
                 version,
                 programId,
                 authority,
                 openOrders,
                 targetOrders,
                 baseVault,
                 quoteVault,
                 marketVersionId,
                 marketProgramId,
                 marketId,
                 marketAuthority,
                 marketBaseVault,
                 marketQuoteVault,
                 marketBids,
                 marketAsks,
                 marketEventQueue,
                 withdrawQueue,
                 lpVault,
                 lookupTableAccount ) VALUES (
                    ${poolKeys.poolId},
                    ${poolKeys.baseMint},
                    ${poolKeys.quoteMint},
                    ${poolKeys.lpMint},
                    ${poolKeys.baseDecimals},
                    ${poolKeys.quoteDecimals},
                    ${poolKeys.lpDecimals},
                    ${poolKeys.version},
                    ${poolKeys.programId},
                    ${poolKeys.authority},
                    ${poolKeys.openOrders},
                    ${poolKeys.targetOrders},
                    ${poolKeys.baseVault},
                    ${poolKeys.quoteVault},
                    ${poolKeys.marketVersionId},
                    ${poolKeys.marketProgramId},
                    ${poolKeys.marketId},
                    ${poolKeys.marketAuthority},
                    ${poolKeys.marketBaseVault},
                    ${poolKeys.marketQuoteVault},
                    ${poolKeys.marketBids},
                    ${poolKeys.marketAsks},
                    ${poolKeys.marketEventQueue},
                    ${poolKeys.withdrawQueue},
                    ${poolKeys.lpVault},
                    ${poolKeys.lookupTableAccount}
                 )`;
  await runQuery(db, sql);
}
