export const CustomEvents = {
  importWalletEvent: 'import-wallet',
  generateWalletEvent: 'generate-wallet',
  saveWalletEvent: 'save-wallet',
  getLatestTransactionsEvent: 'get-latest-transactions',
  getWalletsEvent: 'get-wallets',
  getWalletDetailsEvent: 'get-wallet-details',
  updateWalletEvent: 'update-wallet-info',
  deleteWalletEvent: 'delete-wallet',
  createConnectionEvent: 'create-connection',
  updateActiveConnectionEvent: 'update-active-connection',
  deleteConnectionEvent: 'delete-connection',
  getConnectionsEvent: 'get-connections',
  getTokenDetailsEvent: 'get-token-details',
  getTokensPricesEvent: 'get-token-prices',
  getTokenPriceEvent: 'get-token-price',
  swapEvent: 'swap',
  wrapEvent: 'wrap',
  unwrapEvent: 'unwrap',
  getTokenList: 'get-token-list',
  addTokenEvent: 'add-token',
  getWSOLEvent: 'get-wsol',
  deactivateConnectionEvent: 'deactivate-connection',
  addTokenToFavouritesEvent: 'add-token-to-favourites',
  removeTokenFromFavouritesEvent: 'remove-token-from-favourites',
  simpleTransferEvent: 'simple-transfer',
  tokenTransferEvent: 'token-transfer',
  getPoolFiltersEvent: 'get-pool-filters',
  createTrackProcessEvent: 'create-track-process',
  getTrackProcessesEvent: 'get-track-processes',
  getTrackProcessDetailsEvent:  'get-track-process-details',
  startTrackProcessEvent: 'start-track-process',
  stopTrackProcessEvent: 'stop-track-process',
  updateTrackProcessEvent: 'update-track-process',
  viewTrackProcessEvent: 'view-track-process',
  saveWalletFromTrackProcessEvent: 'save-wallet-from-track-process',
  transactionUpdateEvent: 'transaction-update',
  getDataCollectProcessesEvent: 'get-data-collect-processes',
  getDataCollectProcessDetailsEvent:  'get-data-collect-process-details',
  startDataCollectProcessEvent: 'start-data-collect-process',
  stopDataCollectProcessEvent: 'stop-data-collect-process',
  updateDataCollectProcessEvent: 'update-data-collect-process',
  viewDataCollectProcessEvent: 'view-data-collect-process',
};

export function verifyUniqueEvents(): boolean {
  return true;
}
